### ISSUE TITLE
Bug: Alternativ-ID's werden nicht gespeichert resp. gehen verloren

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-assets-suite#33]
Bei der Erfassung von mehreren Alternativ-ID's über "Neue Alternativ-ID hinzufügen" (Edit-Mode, Tab "Allgemein") kann es vorkommen, dass die neu eingegebenen Angaben beim Speichern verloren gehen / nicht gespeichert werden (Speichern über Tab "Administration"). 

![Image](https://github.com/geoadmin/web-asset-swissgeol/assets/108096632/4d06a8ee-1bdf-41ee-ad31-05c347b3a417)

Dies insbesondere, wenn mehrere Alternativ-ID's ohne jeweilige Zwischenspeicherung zugefügt oder bestehende bearbeitet werden (über die 3 senkrecht angeordneten Punkte, Speichern direkt bei der Bearbeitung im Tab "Allgemein").

1. Bearbeitung starten (über 3 senkrechte Punkte-Menue):

![Image](https://github.com/geoadmin/web-asset-swissgeol/assets/108096632/1b059235-f109-42c6-83aa-f2c2a05bf4ac)

2. Eintrag bearbeiten/ändern und auf "Speichern" klicken:

![Image](https://github.com/geoadmin/web-asset-swissgeol/assets/108096632/483a7335-9ff7-404b-8250-cdc5a11f3f02)

3. Nach dem Speichern verschwindet der Eintrag vollständig:

![Image](https://github.com/geoadmin/web-asset-swissgeol/assets/108096632/03a41400-3bc5-4069-b3fd-e4c0328e9f56)

Die Verwaltung der Alternativ-ID's scheint allgemein noch etwas fehleranfällig und instabil zu sein.

**Acceptance criteria**
1. Editing Alternative ID's works properly
2. After editing, adding and removing Alternative ID's still works properly

**Comment by daniel-va** [comment]
@gysimichael Der Bugfix ist auf dem `dev` zum Testen bereit. Ich konnte den Bug immer reproduzieren indem ich zuerst eine neue Id erfasse & dann eine bestehende bearbeite & speichere. Dies hat immer dazu geführt, dass die bestehende Id gelöscht wird. Dies sollte nun nicht mehr passieren.

**Comment by vej-ananas** [comment]
From PR:
Resolves https://github.com/swisstopo/swissgeol-assets-suite/issues/33.

The bug can reproduced simply by adding a new alternative id, and then editing + saving an existing one. This will cause the id that is being edited to be removed from the form.

Cause:
The fields used to create/edit an alternative id are in a standalone form (i.e. it's not part of the big form that controls the entire asset view). Instead, it's a small form that is "manually" synced back to the big form via observables. This is quite an opaque task with a lot of corner cases. In this case, a subscriber that syncs the two forms was triggered after saving the existing id, but before resetting the small form back to a non-edit state. This caused the subscriber to perceive the id as being "new", and the form as "cancelled", which is why it removes the "cancelled" id.

Solution:
Reorder the state updates so that the subscriber is executed only after the form has been fully reset.

**Comment by mPfifi** [comment]
Auf dev getestet: neu erstellte oder bearbeitete Alternativ-ID's lassen sich direkt über "Speichern" bei ID's speichern und werden nicht mehr gelöscht. Vor Verlassen des Edit-Mode muss zum definitiven Speichern der Änderungen noch im Reiter "Administration" gespeichert werden, was dem normalen Vorgehen entspricht. Sonst erscheint die Warnmeldung vor dem Verlassen des Edit-Mode.

Das Problem scheint somit gelöst zu sein und ich verschiebe den Issue auf Done!
